name: Deploy Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup site config
        run: |
          sed -i 's/<REPO-NAME>/${{ secrets.REPO }}/g' astro.config.mjs
          sed -i 's/<USERNAME>/${{ secrets.USER }}/g' astro.config.mjs
      - name: Deploy with docker
        run: |
          docker build \
            --build-arg TOKEN=${{ secrets.TOKEN }} \
            --build-arg USER=${{ secrets.USER }} \
            --build-arg REPO=${{ secrets.REPO }} \
            --build-arg GIT_DOMAIN=atomgit.com \
            --build-arg BRANCH=pages \
            .
